Feature: Determine the winner of the PawnChess game

  As a player of the PawnChess game
  I want to determine the winner based on the initial board setup
  So that I can know if player A or player B will win when both play optimally

  Rule: Input and Output format
    Given an 8x8 board with 'B' for black pawns, 'W' for white pawns, and '.' for empty cells
    When the board is provided as input
    Then output 'A' if player A (white) wins, or 'B' if player B (black) wins

  Scenario: Player A wins with a clear path
    Given the board:
      """
      ........
      ........
      .B....B.
      ....W...
      ........
      ..W.....
      ........
      ........
      """
    When the game is played optimally
    Then the output should be "A"

  Scenario: Player B wins with a clear path
    Given the board:
      """
      ..B.....
      ..W.....
      ......B.
      ........
      .....W..
      ......B.
      ........
      ........
      """
    When the game is played optimally
    Then the output should be "B"

  Scenario: Player A wins with minimal moves
    Given the board:
      """
      ........
      ........
      ........
      ........
      ........
      ........
      W.......
      ........
      """
    When the game is played optimally
    Then the output should be "A"

  Scenario: Player B wins with minimal moves
    Given the board:
      """
      ........
      ........
      ........
      ........
      ........
      ........
      ........
      .......B
      """
    When the game is played optimally
    Then the output should be "B"

  Scenario: Player A wins with multiple paths
    Given the board:
      """
      ........
      ........
      ........
      ........
      ........
      .W......
      ........
      ........
      """
    When the game is played optimally
    Then the output should be "A"

  Scenario Outline: Determine winner from various board setups
    Given the board:
      """
      <row1>
      <row2>
      <row3>
      <row4>
      <row5>
      <row6>
      <row7>
      <row8>
      """
    When the game is played optimally
    Then the output should be "<winner>"

    Examples:
      | row1      | row2      | row3      | row4      | row5      | row6      | row7      | row8      | winner |
      | ........  | ........  | .B....B.  | ....W...  | ........  | ..W.....  | ........  | ........  | A      |
      | ..B.....  | ..W.....  | ......B.  | ........  | .....W..  | ......B.  | ........  | ........  | B      |
      | ........  | ........  | ........  | ........  | ........  | ........  | W.......  | ........  | A      |
      | ........  | ........  | ........  | ........  | ........  | ........  | ........  | .......B  | B      |
